### ISSUE TITLE
Axis labels not displaying correctly on Heatmap

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTrace#101]
Heatmap looks weird, and axis labels are a blur.
![image](https://user-images.githubusercontent.com/33426295/52011087-0bf01d00-24a5-11e9-800a-39464a82497b.png)

**Comment by AABoyles** [comment]
This one is sort of unfixable. The labels are all bleeding together because there are 134 of the across each axis. Unfortunately, we can't shrink them enough to fix this and keep them legible.

As for the weird appearance of the heatmap itself, it looks like only half of the nodes have any associated distances. This is just a shot in the dark, but I'm guessing you loaded at least two datasets that should have merged, but didn't? I'd confirm the file type (node/link) was identified correctly, that the ID field on file load was set correctly, and that the ID field matched the Source and Target fields of the link list.
