### ISSUE TITLE
Render County from GEOID without a State Column

### ISSUE THREAD

**Issue by AABoyles** [CDCgov/MicrobeTrace#138]

**Comment by jaywokim** [comment]
The five-digit codes of FIPS 6-4 used the two digit FIPS state code (FIPS Publication 5-2, also withdrawn on September 2, 2008), followed by the three digits of the county code within the state or possession. County FIPS codes in the United States are usually (with a few exceptions) in the same sequence as alphabetized county names within a state. They are usually (but not always) odd numbers, so that new or changed county names can be fit in their alphabetical sequence slot.

**Comment by jaywokim** [comment]
based off of source file and code evaluation the requirement is already implemented.
microbetrace uses the fips code against the counties.json to determine coordinate values. It does not require state and county to determine coordinates.

**Comment by jaywokim** [comment]
geo_map.html    line 458
