### ISSUE TITLE
Errant green links on map view

### ISSUE THREAD

**Issue by ells** [CDCgov/MicrobeTrace#149]
![image](https://user-images.githubusercontent.com/1420108/57472673-0c464400-725c-11e9-8af3-136e5327698a.png)

Seem to be the same color as the collapsing map markers?

**Comment by AABoyles** [comment]
OK, the origins of this one are a little bit complicated. This happens when you've got the link color by variable set to "Origin" (which is default when there are multiple files). The 2D network processes the origin variable using a complex custom algorithm to generate the stripey lines. Unfortunately, I don't have as much control over the links in the other views (especially the leaflet- and plotly-based views). Those links are probably from both files, but because leaflet doesn't know what to do with the "both files" data value, it just assigns it a new color. While sort of undesirable, I think any cure will end up being worse than the disease here, so I'm going to call it a wont-fix.
