### ISSUE TITLE
Reorder List in Key/Legend

### ISSUE THREAD

**Issue by ells** [CDCgov/MicrobeTrace#161]
Add the capability to reorder the color-by legend entries. For example, by making the entry draggable so that it can be moved up or down by the user.

**Comment by AABoyles** [comment]
Resolved by 9274c0d03ca8a8a18c2a2d46b935008d4683ac44

**Comment by AABoyles** [comment]
Note that in order to accomplish this, one subtantial and one minor UI tweaks were made. Substantially, The group key table was formally separated into a node colors table and a link colors table. Minorly, in order to make drag-to-reposition work, I needed to turn off the `contenteditable` attribute of the table cells, breaking that functionality. To bring it back, I added the attribute on `dblclick` events, and removed it again on `focusout`. To see this in action, double-click on a cell and type something. Then click (or tab) away from it.
