### ISSUE TITLE
sizing nodes by a variable in 2d does not propogate to 3d view

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTrace#214]
Not sure if this supposed to be a feature, but if 3D view is supposed to also have node sizing, it's not transferring over from 2D

**Comment by jaywokim** [comment]
I looked at this feature and it seems that 2D and 3D have the same sizing by node feature independently in the options for each view. The features that propagate to other open views are usually in the global settings menu and selecting nodes. I think it is best to keep it that way since propagating settings at the view level will introduce problems with precedence and independent control of the feature.

**Comment by jaywokim** [comment]
I can implement this behavior if this feature deserves special treatment.

**Comment by AABoyles** [comment]
FWIW, I strongly agree with @jaywokim. It's supposed to work that way, for exactly the reason he described.
