### ISSUE TITLE
Date field parsing problem when excel file used as input

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTrace#238]
The other day during a demo to CoVID group using their data, the date field was coming up either in the future or a past wrong date. Saving it as a csv and reloading solved the problem.

**Comment by AABoyles** [comment]
One possibility: Excel stores dates as the integer number of days since 1900-01-01, and then applies a date parser when you format the cell as date. MicrobeTrace has no system for dealing with this, but saving the sheet as a CSV transforms the date into what the user sees (which MicrobeTrace usually can parse), rather than the underlying data (which it cannot). Not sure it was the core issue, but something to check.

**Comment by jaywokim** [comment]
thanks Tony!

**Comment by jaywokim** [comment]
added date parsing option in SheetJS method
