### ISSUE TITLE
Stash recall limited to one file only

### ISSUE THREAD

**Issue by odb8-kt** [CDCgov/MicrobeTrace#254]
When recalling stashed files, only one file is available, this being the first stashed file. The recall window doesn't have a list scroll function and when I delete the first file there are no other files available. See attached image of the recall window.
<img width="377" alt="Stash issue" src="https://user-images.githubusercontent.com/68611358/88205075-3ba35f80-cc1a-11ea-8925-1091c680b10b.png">

**Comment by AABoyles** [comment]
Thanks a lot, @odb8-kt! I can confirmed that this bug is replicable. @jaywokim, Looks like the first session object is large enough to tap out the entire LocalStorage allotment.

Proposed solution: Transition from LocalStorage to [LocalForage](https://localforage.github.io/localForage/), which should leverage IndexedDB where possible, and invisibly fall back to LocalStorage if it fails.
