### ISSUE TITLE
Recalling a session while a network is loaded doesn't flush the loaded network

### ISSUE THREAD

**Issue by roxycintron** [CDCgov/MicrobeTrace#285]
Overlapping over existing network after recall

**Comment by roxycintron** [comment]
Ells mentioned this bug in MT Dev meeting 10/15/20

**Comment by billswitzer2** [comment]
I thought this was fixed in Dev.

**Comment by AABoyles** [comment]
Nope, it's still there.

**Comment by AABoyles** [comment]
OK, did a little research. The problem is in the recall function ([common.js#L479](https://github.com/CDCgov/MicrobeTrace/blob/master/src/common.js#L477)-ish). For some reason, it doesn't call `MT.reset` (probably has something to do with old session files). To fix this, we may need to version bump and note that there's a breaking change, so much older session files may not work.

**Comment by billswitzer2** [comment]
Thanks Tony!

**Comment by wje7-cdc** [comment]
Hi Tony, do you suggest to call MT.reset before applying the old session data?

**Comment by AABoyles** [comment]
@mchiuw Yes, like first thing in the recall function.
