### ISSUE TITLE
secondary link file coloring in 3-D is always light green

### ISSUE THREAD

**Issue by AndrewLangvt** [CDCgov/MicrobeTrace#293]
With two link files, the color of the second file is always a light green, even if I set it as a different color. Can this be adjusted to reflect different (user-input) color schemes by link file? 

![Microbetrace_color_3dLinks](https://user-images.githubusercontent.com/14237488/98584852-6df1cf00-2294-11eb-9a19-5a7ffe0d73f9.PNG)

**Comment by roxycintron** [comment]
Other 3D network issues #27  and #28

**Comment by ells** [comment]
@AndrewLangvt Can you describe more of how you reached this state? I've been unable to replicate it myself.

Also, was this in Production (microbetrace.cdc.gov) or was this in dev (https://cdcgov.github.io/MicrobeTrace)?

**Comment by AndrewLangvt** [comment]
@ells this came about as I was trying to load in some bedlog data, though I was adding it as a second pairwise list, very similar to the pairwise SNP list. Following our conversation, I now can add the bedlog info by including it as a link list of individual-bed. Now that I see that what I did here was basically provide two separate lists identifying distance between the same set of individuals, I'm not entirely sure when this scenario would be needed.  You can replicate it with the example link lists below, though I'm not sure this needs to remain an open issue.

Example Pairwise SNP List
```
Source,Target,Distance
Sample1,Sample2,2
Sample1,Sample3,4
Sample1,Sample4,0
Sample2,Sample3,1
```

Example Pairwise Links list
```
Source,Target
Sample1,Sample2
Sample1,Sample4

**Comment by ells** [comment]
@AndrewLangvt 

The reason it always defaults to this color is because it is not recognizing it as a link derived from two origins (pairwise snps and pairwise links), but as a third type of link that is the concatenation of the two types.

In the 2D view, we have the capability to recognize this concatenated link as a separate type. We then hash the lines, and ensure that they appear as two-colored hashed lines...instead of a unique third type. 

This capability would be quite difficult to emulate in three dimensions...similar to attempting to replicate three dimensional shapes. 

For these reasons, I'm going to tag this issue as 'Wont-Fix' and close it out. 

To address this visual issue yourself, I recommend exporting the link list from the Table View, and generating a new 'type' to color links by based on the exported 'Origin' column. This way, you can select discrete mappings for each edge type that will be reflected across the 2D and 3D views.

**Comment by ells** [comment]
@AABoyles should I leave the 'bug' flag here after we've identified and decided not to resolve?

**Comment by AABoyles** [comment]
Yes, still a bug even if it's a wontfix

**Comment by AndrewLangvt** [comment]
This makes sense gang. Thanks for taking a look!
