### ISSUE TITLE
Split up network animation across RequestAnimationFrame calls

### ISSUE THREAD

**Issue by AABoyles** [CDCgov/MicrobeTrace#301]
See https://gist.github.com/DavidBruant/6489486 for an example. May improve 2D network performance on large graphs.

**Comment by wje7-cdc** [comment]
Thanks, @AABoyles. I tried to implement it but have hard time to get codes to work which might be of two types of tick functions we have – regular and polygon. I also dug up the old discussing thread at https://github.com/d3/d3/issues/1519, and this issue was proposed back on 2013 and has been closed for a while. People are using either static force layout which don’t think we are adapting it or WebWorker which I will need to get codes working before trying it out. Will resume when time permits…

**Comment by AABoyles** [comment]
I wouldn't invest a lot of effort in it, tbh. [I looked into this strategy independently](https://anthony.boyles.cc/Network-Demos/#requestanimationframe-svg-canvas) and couldn't get any performance improvements out of it either. It looks like D3 is pretty hyper-optimized already, and the only way to really relieve the animation bottleneck is to transition to canvas 🤷
