### ISSUE TITLE
Separate downloads by cluster

### ISSUE THREAD

**Issue by ells** [CDCgov/MicrobeTrace#361]
As a user, I need to be able to download all information about a single cluster (rather than all at once). Therefore, I need a download option that creates a zipped directory of node and edge lists for each cluster.

If I have 5 clusters, I want a zipped file with:
1.) Five folders, one for each cluster with "cluster [clusterID]" as the directory name
2.) One nodelist_[clusterID].csv file
3.) One edgelist_[clusterID].csv file

**Comment by billswitzer2** [comment]
Thanks!

From: Ellsworth Campbell ***@***.***>
Sent: Wednesday, April 21, 2021 3:03 PM
To: CDCgov/MicrobeTrace ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [CDCgov/MicrobeTrace] Separate downloads by cluster (#361)


As a MicrobeTrace user, I need to be able to download all information about a single cluster (rather than all at once). Therefore, I need a download option that creates a zipped directory of node and edge lists for each cluster.

If I have 5 clusters, I want a zipped file with:
1.) Five folders, one for each cluster with "cluster [clusterID]" as the directory name
2.) One nodelist_[clusterID].csv file
3.) One edgelist_[clusterID].csv file

**Comment by mossy426-cdc** [comment]
I'm finding that I can zip files together, but to create folder structures seems to be a server-side feature with node.js.  Been researching for some time and haven't come across something that will allow it clientside.  Though there is a package that allows the clientside to run nodejs modules which might do the trick.

**Comment by mossy426-cdc** [comment]
Actually found a library that might do the trick called JSZip. 

https://github.com/Stuk/jszip

  Will have to inspect it for security vulnerabilities.

**Comment by mossy426-cdc** [comment]
Found an issue where saving a session file would save it as a .session extension instead of a microbetrace extension.  The issue has since been resolved.
