### ISSUE TITLE
Link labels remain at the start of timeline 

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTrace#377]
If you turn on link labels via Settings, then they are displayed as expected. However, when I go in to time player, then, at the start, even before I hit play, you can see the link labels. No nodes, no links, but link labels remain.
![LinkLabelsStay.JPG](https://images.zenhubusercontent.com/60873227d0d25c1fe3daadb1/663cc369-e113-4a88-bb31-cece57a35dfb)

**Comment by frankambrosio3** [comment]
Resolution will be to hide all labels at the beginning of timeline and they will reappear as the nodes and links that they belong to appear over time.

**Comment by ikb6** [comment]
This issue still remains

![image.png](https://images.zenhubusercontent.com/60873227d0d25c1fe3daadb1/65d1aab9-e659-4bec-83fb-e92073c132ec)

**Comment by ikb6** [comment]
This issue still persists

![Zenhub377.PNG](https://images.zenhubusercontent.com/60873227d0d25c1fe3daadb1/29d1f494-cd47-40e3-93c8-283897a15f7c)

**Comment by mossy426-cdc** [comment]
The function that was displaying text for the links was throwing an error and causing them all to appear.  The issue was that the links being iterated through were all links, not all visible links, so it would add text to links that didn't exist and would through the error.  It now retrieves the proper links and displays correctly.
