### ISSUE TITLE
Dashboard is not saved in session (.microbetrace) file

### ISSUE THREAD

**Issue by roxycintron** [CDCgov/MicrobeTRACE#549]
This issue applies to both MT and HN. 

When dashboard with several views is saved as session file and this session file is imported into MT or HN, only the 2D network is re-loaded. However, the features in the other views are saved if you re-open them. 

To reproduce the error:

1. Open HN, create dashboard with 2D network and phylogenetic tree views and save as "Test-Dashboard.microbetrace" (session file).

![image.png](https://images.zenhubusercontent.com/607a02e552f324d422b2175a/dfef9fc1-9ab4-4df4-8fc7-546504ad8360)

2. Load the saved "Test-Dashboard.microbetrace" file into MT or HN and see that the 2D network view is loaded.

![image.png](https://images.zenhubusercontent.com/607a02e552f324d422b2175a/e7fff975-691c-4fb1-a9b7-157a7a9cf8cd)

[https://app.zenhub.com/files/149786212/9e2b319e-42bb-4efe-9546-6a5551feef5a/download]

**Comment by mossy426-cdc** [comment]
Hey Roxy, want to confirm if this was ever a possibility before and it just stopped working at some point?  I've never seen a session loaded where multiple views were visible at once.  If not, this should be a feature enhancement rather than a bug.

EDIT.  I do see the phylo tree is missing in the tab, so it is a bug.  Just not sure whether the fix is just to make sure the view is in there with the tabs, or have it also display everything at once.
