### ISSUE TITLE
Size By Doesn't Work with Number Fields from Node List

### ISSUE THREAD

**Issue by qqh3-cdc** [CDCgov/MicrobeTRACE#687]
Upload node list with age field. Change the Node Size by and Size settings.
![image.png](https://images.zenhubusercontent.com/649cc14090d9753a7231ea3b/e00d39ac-c066-4e16-8f29-afae7dac2f8b)
Visualization does not reflect size of cluster based on age.

Also, changing size slider does nothing on visualization.
![image.png](https://images.zenhubusercontent.com/649cc14090d9753a7231ea3b/0e7000da-488b-4f08-aca9-b517d2c03101)

 - OS: PC
 - Browser: Edge
 - Version: 114.0.1823.67

**Comment by mossy426-cdc** [comment]
For this, the size row is only meant to be displayed when the Size By value is set to none, as it changes the size for all nodes.  When SizeBy is assigned a value, then min and max size should appear and size should dissappear since it shouldn;t affect all nodes anymore.  It has the hiding funtionality in the code, but it was referencing an id for the size element that did not exist.  I've added the id to the element and now it hides/shows as expected.
