### ISSUE TITLE
ANGULAR: "Show color" button in Node settings does not work

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#697]
Clicking on the show color button under node settings (not Global Settings menu), does not do anything.

See video sent with issue number

**Comment by mossy426-cdc** [comment]
Clicking the "show color" button emits an event from the 2d network.  The main wrapper component is supposed to see this event happen and then open global settings.  The issue is that the main wrapper is not subscribed to the event from the 2d network, so it does not see the event.  I've added the subscription and it works as expected.  Will push the changes soon.
