### ISSUE TITLE
MTDEV and MTPROD- node colors change when network re-renders after distance threshold is modified

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#743]
Used a session file. setting was initially 0.015, nodes colored by subtype, then threshold was changed to 0.025, network re-rendered and now the colors were different. Not all, only some. See video emailed to you with Issue number in subject line

**Comment by mossy426-cdc** [comment]
Took me a bit to figure out why this was having issues.  At first I thought it was because it's a session file, but it seems its the fact that the minimum cluster size is 2.  I remember a while back that I think filtering wasn't allowed when the minimum cluster size was not equal to 1.  It would result in a number of issues after filtering as it affects all the calculations. This may take some time, but its more than just the colors being diffrent that will be an issue. 

I believe the most efficient way would be to return to the previous state where you couldn't filter when min cluster size wasn't 1.  Filter whatever threshold you want, and then change the min cluster size.  You can change cluster size back to filter more and then repeat when you have the threshold you want an want to hide the smaller cluster sizes.
