### ISSUE TITLE
ANGULAR: Issues with manipulating a loaded session file

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#744]
When I load a session file (created in MTDEV) into Angular, I noticed that it mis-reads the source files (Thinks it is a link list instead of a nodelist- see image 1 below). However, network is displayed correctly. When I try to increase threshold, nothing happens- no change to network (number of clusters and links should increase).
When I go to Files tab and correct the source files from Link to Node, and re-launch, then all links disappear (see img 2  below)
To reproduce:

- See session file created in MTDEV. You can find it in Teams folder here
- https://cdc.sharepoint.com/:u:/r/teams/nchhstp-dhap-lb-microbetrace/Shared%20Documents/General/Files%20for%20bug%20reports/DGHT_NG_PRRT.microbetrace?csf=1&web=1&e=cfhac1
- Source files used for the session are two nodelists and one FASTA file
- Open in Angular
- Adjust dist threshold
- Go to Files tab and see source files
- Observe network
IMG 1
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekdLQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fc77a2901ace330ed9d3b14e91b8814f50422657/Angular_Sessionfile_FileTypeMisread.JPG)

IMG2

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBektLQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f9df043c2f728ba4544ed81e67efed42a20e2d45/SEssion_file_CorrectFileTypeMistakeUpdatedNetwork.JPG)

**Comment by mossy426-cdc** [comment]
The issue here was that the threshold change was calling undefined funcitons in this scenario and not performing calculations.  I've updated it to be the appropriate functions and it seems to be good.

Another issue with the node format turning into link was that the "isNode" check only had the implementation to make the file a node type if it had the word "node" in the file name and no check for a previously saved format. I've added that as well.
