### ISSUE TITLE
ANGULAR vs PROD Distance matrix parsing seems to have a glitch in PROD

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#749]
When you load a distance matrix in PROD that has a text value in cell A1 (a header), it thinks of it as a node and creates artifacts, and the network looks weird. When that header cell is deleted the network is correct (David's email)
Angular is able to recognize that cell A1 contains random text and does not count it as a node. It process the matrix correctly JPEG files are below

https://cdc.sharepoint.com/:f:/r/teams/nchhstp-dhap-lb-microbetrace/Shared%20Documents/General/Files%20for%20bug%20reports?csf=1&web=1&e=huTWro

**Comment by mossy426-cdc** [comment]
I've found the issue.  In the prod code there is this extra condition with the comment of "triangle matrix" and this essenitlly adds on an empty node at the beginning of the nodes list prior to pruning.  The nodes list prunes off the first node since that is the top left corner of the matrix and should be avoided, but since there is an empty node now input at the beggining, that gets pruned off instead of the node/1st cell.  That is why we are seeing it.  I am not usre as to what this triangle functionality is for, as it's not in Angular and not sure what the need for it is.  Maybe we can ask tony.

 [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3doQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1def76aa00a66e8c6b046e2de606900540fe2fb3/Screenshot%202023-11-30%20at%2012.16.36%20PM.png)
