### ISSUE TITLE
Angular: Tiling needed

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#791]
Now that we have multiple views, we should add tiling functionality in the mossy version. From prior experience, we know it could raise issues, so better to add now, and do extensive testing.

**Comment by dacowan404** [comment]
Made several changes so that view are sized according to the space they are given when tiling, settings and export dialog boxes don't appear behind other views, and node-selected events (by clicking on a node) is synchronized between 2D network, map, table, and alignment views (additional work is needed to synchronize tree view.)
