### ISSUE TITLE
Link list repeats a node and builds wrong network

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#803]
This bug was emailed to me by a user. I got on a call with him, copy pasted the cells into a blank csv, saved and used it. That seemed to fix it then, but he tried doing it and that fix is not working for him. Could you check the CSV file at  link below and see what could be corrupted? 

Trouble sharing link- please see email for attachments

[https://cdc.sharepoint.com/:x:/r/teams/nchhstp-dhap-lb-microbetrace/Shared%20Documents/General/Files%20for%20bug%20reports/Issue803_microbetrace_link_test_Nelson.csv?d=wbc45579b6b97477994810c2262cd8813&csf=1&web=1&e=HuHLqf](url)

Wrong network

<img width="1530" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN21PQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d7eb821c0083306047dae74e85d28c72cd0645eb/Neslson_test_link_bug.JPG" alt="Neslson_test_link_bug.JPG" />

Correct network after copy pasting
<img width="1344" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3FPQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--02909b32ab92379c62c7118497f258bfa6e9eb43/Nelson_correct_network.JPG" alt="Nelson_correct_network.JPG" />

**Comment by dacowan404** [comment]
The csv file that you sent has a space before all the values in the target column. So MicrobeTrace is interpreting "AC001" and " AC001" as different node names. In the short term, he could trim function in excel to get rid of these whitespaces. When I did that I got the correct network except link be AB001 and AC003 which isn't in CSV. This is probably just a typo because link between AB001 and AC001 is in the CSV twice. 
I thought MicrobeTrace had this functionality to remove whitespace at start and end.

**Comment by billswitzer2** [comment]
Thanks David!

**Comment by ikb6** [comment]
Ah, great catch, thanks David!

**Comment by dacowan404** [comment]
@ikb6 I have updated the angular version to trim whitespaces from node names. It is currently deployed on the mossy site, so you should be able to use the original file that was causing this bug
