### ISSUE TITLE
PROD: MT thinks a distance matrix is an edge list

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#806]
This is an issue reported by a user. She managed to load the network, but when she goes back to the File Add tab, she notices that it is displaying as an edge list again. Files she provided are at the link below
A note- when I try to load her distance matrix into PROD, MT thinks it's an edge list. Even though I correct the file type to Matrix, the network has no links. ANGULAR  is able to parse the file correctly once I tell it that it is a distance matrix

https://cdc.sharepoint.com/:f:/r/teams/nchhstp-dhap-lb-microbetrace/Shared%20Documents/General/Files%20for%20bug%20reports/VA-N.meningitidis%20support/VA-Nmenigitidis?csf=1&web=1&e=GPe5TL

Attached is the SNP distance matrix file (from a WGS bioinformatic analysis performed by CDC) that I am using.  I am able to change the distance metric to SNPs, and set the threshold at 33 (this is the Nm lab’s best guess at a threshold, but I filtered to only 20 SNPs in this viz).  However, if/when I go back to the add data window, Microbetrace appears to be reading my distance matrix file as an Edge list without any specified distances…This makes no sense to me, since – as you will see in this session file – it still displays the SNPs properly.  If you can = please clarify, confirm for me that the software is reading my SNP distance matrix file correctly (?)….
Thank you!!
 
<img width="756" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMW13QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c435bb27e1c0a2def11915ea4a62abcc6ff825dc/image.png" alt="image.png" />

**Comment by billswitzer2** [comment]
Confirm that MT Prod thinks it is an edge list and not matrix. I get this network when choosing matrix, SNP and 16 for threshold before launching.
***@***.***
Confirm that add data shows original file reverts to edge list.
***@***.***
From: ikb6 ***@***.***>
Sent: Thursday, May 2, 2024 2:11 PM
To: CDCgov/MicrobeTrace ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [CDCgov/MicrobeTrace] PROD: MT thinks a distance matrix is an edge list (Issue #806)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.
________________________________


This is an issue reported by a user. She managed to load the network, but when she goes back to the File Add tab, she notices that it is displaying as an edge list again. Files she provided are at the link below
A note- when I try to load her distance matrix into PROD, MT thinks it's an edge list. Even though I correct the file type to Matrix, the network has no links. ANGULAR is able to parse the file correctly once I tell it that it is a distance matrix

https://cdc.sharepoint.com/:f:/r/teams/nchhstp-dhap-lb-microbetrace/Shared%20Documents/General/Files%20for%20bug%20reports/VA-N.meningitidis%20support/VA-Nmenigitidis?csf=1&web=1&e=GPe5TL

Attached is the SNP distance matrix file (from a WGS bioinformatic analysis performed by CDC) that I am using. I am able to change the distance metric to SNPs, and set the threshold at 33 (this is the Nm lab’s best guess at a threshold, but I filtered to only 20 SNPs in this viz). However, if/when I go back to the add data window, Microbetrace appears to be reading my distance matrix file as an Edge list without any specified distances…This makes no sense to me, since – as you will see in this session file – it still displays the SNPs properly. If you can = please clarify, confirm for me that the software is reading my SNP distance matrix file correctly (?)….
Thank you!!

[https://camo.githubusercontent.com/96b4b904f97a45f3cb75814b762d0319236cb630300b1bda1eea574d4bf8f005/68747470733a2f2f6170692e7a656e6875622e636f6d2f617474616368656446696c65732f65794a66636d467062484d694f6e73696257567a6332466e5a534936496b4a42614842424d573133516b453950534973496d563463434936626e56736243776963485679496a6f69596d7876596c39705a434a3966513d3d2d2d633433356262323765316330613264656631313931356561346136326162636336666638323564632f696d6167652e706e67]<https://camo.githubusercontent.com/96b4b904f97a45f3cb75814b762d0319236cb630300b1bda1eea574d4bf8f005/68747470733a2f2f6170692e7a656e6875622e636f6d2f617474616368656446696c65732f65794a66636d467062484d694f6e73696257567a6332466e5a534936496b4a42614842424d573133516b453950534973496d563463434936626e56736243776963485679496a6f69596d7876596c39705a434a3966513d3d2d2d633433356262323765316330613264656631313931356561346136326162636336666638323564632f696d6167652e706e67>

**Comment by ikb6** [comment]
Converting it to a CSV solves the issue.
